'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:2.0.50727.3082
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------
Namespace LinqServerModeOnAdvWorks.Properties

    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")>
    Friend NotInheritable Partial Class Settings
        Inherits Global.System.Configuration.ApplicationSettingsBase

        Private Shared defaultInstance As LinqServerModeOnAdvWorks.Properties.Settings = CType((Global.System.Configuration.ApplicationSettingsBase.Synchronized(New LinqServerModeOnAdvWorks.Properties.Settings())), LinqServerModeOnAdvWorks.Properties.Settings)

        Public Shared ReadOnly Property [Default] As Settings
            Get
                Return LinqServerModeOnAdvWorks.Properties.Settings.defaultInstance
            End Get
        End Property

        <Global.System.Configuration.ApplicationScopedSettingAttribute()>
        <Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>
        <Global.System.Configuration.SpecialSettingAttribute(Global.System.Configuration.SpecialSetting.ConnectionString)>
        <Global.System.Configuration.DefaultSettingValueAttribute("Data Source=(local);Initial Catalog=AdventureWorks;Integrated Security=True")>
        Public ReadOnly Property AdventureWorksConnectionString As String
            Get
                Return(CStr((Me("AdventureWorksConnectionString"))))
            End Get
        End Property
    End Class
End Namespace
